[package]
name = "doca-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.5", features = ["multipart"] }
tokio = { version = "1.38", features = ["full"] }
tower-http = { version = "0.5.2", features = ["cors", "compression-full"] }
lopdf = "0.44.0"
printpdf = { version = "0.12.5", features = ["images"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
zeroize = "1.7"
office2pdf = "0.6.5"
chrono = { version = "0.4.38", default-features = false, features = ["clock", "std"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[patch.crates-io]
quick-xml = { git = "https://github.com/tafia/quick-xml", tag = "v0.41.0" }




